version: '3'
networks:
  homeassistant:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.27.99.0/24
          gateway: 172.27.99.1
services:
  mosquitto:
      image: "eclipse-mosquitto:1.6"
      container_name: mosquitto
      restart: unless-stopped
      volumes:
        - mosquitto-config:/mosquitto/config
        - mosquitto-data:/mosquitto/data
        - mosquitto-log:/mosquitto/log
        - /etc/localtime:/etc/localtime:ro
      networks:
        homeassistant:
          ipv4_address: 172.27.99.6
      ports:
        - 1883:1883
  acurite2mqtt:
      container_name: acurite
      image: 31e5450e7115
      networks:
        homeassistant:
          ipv4_address: 172.27.99.7
      volumes:
        - 31e5450e7115:/data/
      environment:
          MQTT_HOST: "192.168.0.50"
          MQTT_PORT: "1883"
          MQTT_USER: "user"
          MQTT_PASSWORD: "password"
          MQTT_RETAIN: "true"
          MQTT_TOPIC: "rtl_433"
          PROTOCOL: "-R 11 -R 40 -R 41 -R 55 -R 74"
          UNITS: "customary"
          EXPIRE_AFTER: 60
          DISCOVERY_PREFIX: "homeassistant"
          DISCOVERY_INTERVAL: 600
          WHITELIST_ENABLE: "false"
          WHITELIST: ""
          DEBUG: "false"
      restart: unless-stopped
volumes:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
  31e5450e7115: